import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config({ path: '.env' });

const supabase = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.VITE_SUPABASE_ANON_KEY
);

// ── Legions ──────────────────────────────────────────────────────────────────

const legions = [
  {
    id: 'leg-x-fretensis',
    name: 'Legio X Fretensis',
    number: 'X',
    cognomen: 'Fretensis',
    founded_year: '41 BC',
    founder: 'Octavian',
    main_theater: 'Judaea, Syria',
    emblem: 'Bull, Ship, Boar',
    symbol_description: 'Associated with the Straits of Messina (Fretum Siculum)',
    status: 'Last Attested',
    certainty: 'Confirmed',
    era: 'Principate',
    description: 'One of the most famous legions of the Imperial era, central to the Siege of Jerusalem and the fall of Masada.',
    last_attestation: 'Early 5th Century (Notitia Dignitatum)',
    fate: 'Last recorded at Aila (modern Aqaba) guarding the Red Sea.',
    book_title: 'Legio X Fretensis: A Prosopographical Study',
    book_author: 'Edward Dabrowa',
    book_url: 'https://www.amazon.com/s?k=Legio+X+Fretensis+Dabrowa',
    active_period: '41 BC – after AD 410',
    garrison_hq: ['Judaea (20s BC)', 'Syria (c. 6 – 66)', 'Jerusalem (c. 73 – late 3rd century)', 'Aila (late 3rd century – after 410s)'],
    nicknames: 'Fretensis, "of the sea strait"',
    mascots: ['Bull', 'Ship', 'Neptune', 'Boar'],
    engagements: ['Battle of Naulochus (36 BC)', 'Battle of Actium (31 BC)', 'Corbulo Parthian campaign', 'First Jewish-Roman War (66–73)', 'Siege of Masada (72–73)', 'Trajan Parthian campaign', 'Bar Kokhba revolt (132–135)'],
    notable_commanders: ['Gnaeus Domitius Corbulo', 'Vespasian', 'Titus', 'Sextus Lucilius Bassus', 'Trajan', 'Sextus Julius Severus'],
  },
  {
    id: 'leg-ix-hispana',
    name: 'Legio IX Hispana',
    number: 'IX',
    cognomen: 'Hispana',
    founded_year: '65 BC',
    founder: 'Pompey or Caesar',
    main_theater: 'Britain, Rhine',
    emblem: 'Bull',
    symbol_description: 'Standard bull emblem of Caesarian legions',
    status: 'Destroyed',
    certainty: 'Disputed',
    era: 'Principate',
    description: 'The "Lost Legion" of popular fiction. It famously disappeared from the record after serving in Roman Britain.',
    last_attestation: 'c. 120 AD',
    fate: 'Disappeared. Theories range from destruction in Scotland to relocation and destruction in the East (Bar Kokhba revolt).',
    book_title: 'The Eagle of the Ninth',
    book_author: 'Rosemary Sutcliff',
    book_url: 'https://www.amazon.com/s?k=Eagle+of+the+Ninth+Sutcliff',
    active_period: '65 BC – c. AD 120',
    garrison_hq: ['Hispania (65–43 BC)', 'Pannonia (9 BC–43 AD)', 'Eboracum / York (71–108 AD)', 'Nijmegen (c. 108–120 AD)'],
    nicknames: 'Hispana, "the Spanish"',
    mascots: ['Bull'],
    engagements: ['Gallic Wars', 'Battle of Pharsalus (48 BC)', 'Conquest of Britain (43 AD)', 'Boudicean revolt (60–61 AD)', 'Year of the Four Emperors (69 AD)'],
    notable_commanders: ['Julius Caesar', 'Quintus Petronius Turpilianus', 'Quintus Petillius Cerialis'],
  },
  {
    id: 'leg-xx-valeria',
    name: 'Legio XX Valeria Victrix',
    number: 'XX',
    cognomen: 'Valeria Victrix',
    founded_year: '31 BC',
    founder: 'Augustus',
    main_theater: 'Britain, Germania',
    emblem: 'Boar',
    symbol_description: 'The charging boar symbol, granted for valor',
    status: 'Active',
    certainty: 'Confirmed',
    era: 'Principate',
    description: 'A stalwart of the British frontier, based for centuries at Deva Victrix (Chester).',
    last_attestation: 'Late 4th Century',
    fate: 'Likely withdrawn to the continent or dissolved during the Western collapse.',
    book_title: null, book_author: null, book_url: null,
    active_period: '31 BC – late 4th century AD',
    garrison_hq: ['Cologne (Germania)', 'Camulodunum / Colchester (43–49 AD)', 'Glevum / Gloucester (49–66 AD)', 'Deva Victrix / Chester (c. 87 AD onwards)'],
    nicknames: 'Valeria Victrix, "the Valiant and Victorious"',
    mascots: ['Boar'],
    engagements: ['Conquest of Britain (43 AD)', 'Boudicean revolt (60–61 AD)', 'Agricolan campaigns in Scotland (77–84 AD)', 'Severan campaigns (208–211 AD)'],
    notable_commanders: ['Gnaeus Julius Agricola', 'Marcus Atilius Metilius Bradua'],
  },
  {
    id: 'leg-iii-gallica',
    name: 'Legio III Gallica',
    number: 'III',
    cognomen: 'Gallica',
    founded_year: '49 BC',
    founder: 'Julius Caesar',
    main_theater: 'Syria, Phoenicia',
    emblem: 'Bull',
    symbol_description: 'Standard bull emblem',
    status: 'Active',
    certainty: 'Confirmed',
    era: 'Late Republic',
    description: 'Known for its fierce loyalty to the Syrian frontier and often decisive in imperial successions.',
    last_attestation: 'Uncertain',
    fate: 'Replaced or dissolved during the restructuring of the Byzantine military.',
    book_title: null, book_author: null, book_url: null,
    active_period: '49 BC – 4th century AD',
    garrison_hq: ['Syria (from 30s BC)', 'Raphanaea, Syria', 'Danube frontier (briefly, 69 AD)', 'Phoenicia (3rd century AD)'],
    nicknames: 'Gallica, "the Gallic"',
    mascots: ['Bull'],
    engagements: ['Gallic Wars', 'Battle of Pharsalus (48 BC)', 'Battle of Actium (31 BC)', 'Corbulo Parthian campaign (58–63 AD)', 'Year of the Four Emperors (69 AD)', 'Severan civil wars'],
    notable_commanders: ['Mark Antony', 'Gnaeus Domitius Corbulo', 'Gaius Cassius Longinus'],
  },
  {
    id: 'leg-xvii',
    name: 'Legio XVII',
    number: 'XVII',
    cognomen: 'Destroyed / Teutoburg',
    founded_year: '41 BC',
    founder: 'Octavian',
    main_theater: 'Germania Magna',
    emblem: 'None Recovered',
    symbol_description: 'Lost in Teutoburg Forest',
    status: 'Destroyed',
    certainty: 'Confirmed',
    era: 'Principate',
    description: 'ANNIHILATED in the Teutoburg Forest (AD 9). The number XVII was never used again as it was considered accursed.',
    last_attestation: 'AD 9',
    fate: 'Total annihilation at the hands of Arminius.',
    book_title: null, book_author: null, book_url: null,
    active_period: '41 BC – AD 9',
    garrison_hq: ['Rhine frontier', 'Vetera / Xanten (Germania Inferior)'],
    nicknames: null,
    mascots: [],
    engagements: ['Battle of the Teutoburg Forest (AD 9)'],
    notable_commanders: ['Publius Quinctilius Varus'],
  },
  {
    id: 'leg-xviii',
    name: 'Legio XVIII',
    number: 'XVIII',
    cognomen: 'Destroyed / Teutoburg',
    founded_year: '41 BC',
    founder: 'Octavian',
    main_theater: 'Germania Magna',
    emblem: 'None Recovered',
    symbol_description: 'Lost in Teutoburg Forest',
    status: 'Destroyed',
    certainty: 'Confirmed',
    era: 'Principate',
    description: 'Along with the XVII and XIX, this legion was wiped out in the AD 9 disaster. Its eagle was not recovered for years.',
    last_attestation: 'AD 9',
    fate: 'Total annihilation in Germania AD 9.',
    book_title: null, book_author: null, book_url: null,
    active_period: '41 BC – AD 9',
    garrison_hq: ['Rhine frontier', 'Vetera / Xanten (Germania Inferior)'],
    nicknames: null,
    mascots: [],
    engagements: ['Battle of the Teutoburg Forest (AD 9)'],
    notable_commanders: ['Publius Quinctilius Varus'],
  },
  {
    id: 'leg-xix',
    name: 'Legio XIX',
    number: 'XIX',
    cognomen: 'Destroyed / Teutoburg',
    founded_year: '41 BC',
    founder: 'Octavian',
    main_theater: 'Germania Magna',
    emblem: 'None Recovered',
    symbol_description: 'Lost in Teutoburg Forest',
    status: 'Destroyed',
    certainty: 'Confirmed',
    era: 'Principate',
    description: 'The third leg of the Varus disaster. Its lost aquila (eagle) was recaptured by the Romans decades later.',
    last_attestation: 'AD 9',
    fate: 'Total annihilation in the Teutoburg ambush AD 9.',
    book_title: null, book_author: null, book_url: null,
    active_period: '41 BC – AD 9',
    garrison_hq: ['Rhine frontier', 'Vetera / Xanten (Germania Inferior)'],
    nicknames: null,
    mascots: [],
    engagements: ['Battle of the Teutoburg Forest (AD 9)'],
    notable_commanders: ['Publius Quinctilius Varus'],
  },
  {
    id: 'leg-v-alaudae',
    name: 'Legio V Alaudae',
    number: 'V',
    cognomen: 'Alaudae',
    founded_year: '52 BC',
    founder: 'Julius Caesar',
    main_theater: 'Dacia, Moesia',
    emblem: 'Elephant',
    symbol_description: 'The Larks (Alaudae)',
    status: 'Destroyed',
    certainty: 'Probable',
    era: 'Principate',
    description: 'The first legion composed of non-citizens (Gauls). Fought with distinction but was likely destroyed in Dacia.',
    last_attestation: 'AD 86',
    fate: 'Likely wiped out during the Dacian King Decebalus invasion of Moesia.',
    book_title: null, book_author: null, book_url: null,
    active_period: '52 BC – c. AD 86',
    garrison_hq: ['Hispania (after 45 BC)', 'Lower Rhine (Germania Inferior)', 'Moesia (1st century AD)'],
    nicknames: 'Alaudae, "the Larks"',
    mascots: ['Elephant'],
    engagements: ['Gallic Wars (58–50 BC)', 'Battle of Thapsus (46 BC)', 'Battle of Actium (31 BC)', 'Rhine campaigns', 'First Dacian War (c. 86 AD)'],
    notable_commanders: ['Julius Caesar', 'Mark Antony'],
  },
  {
    id: 'leg-xxii-deiotariana',
    name: 'Legio XXII Deiotariana',
    number: 'XXII',
    cognomen: 'Deiotariana',
    founded_year: '48 BC',
    founder: 'Deiotarus (King of Galatia)',
    main_theater: 'Egypt, Judaea',
    emblem: 'None Record',
    symbol_description: 'Named after its royal founder',
    status: 'Destroyed',
    certainty: 'Disputed',
    era: 'Principate',
    description: 'A legion with Eastern roots. It vanished from history around the Bar Kokhba revolt.',
    last_attestation: 'AD 119/123',
    fate: 'Commonly thought to have been destroyed during the Bar Kokhba revolt (AD 132-135).',
    book_title: null, book_author: null, book_url: null,
    active_period: '48 BC – c. AD 135',
    garrison_hq: ['Galatia (founded here)', 'Alexandria, Egypt (from c. 25 BC)', 'Judaea (2nd century AD)'],
    nicknames: 'Deiotariana, "of Deiotarus"',
    mascots: [],
    engagements: ['Battle of Actium (31 BC)', 'Jewish-Roman Wars', 'Bar Kokhba revolt (132–135 AD)'],
    notable_commanders: ['King Deiotarus of Galatia'],
  },
];

// ── Movement Stages ───────────────────────────────────────────────────────────

const stages = [
  {
    id: 'stage-1',
    legion_id: 'leg-x-fretensis',
    year: '41 BC',
    location: 'Sicily / Straits of Messina',
    description: 'Founded by Octavian for the war against Sextus Pompey. Earned the title "Fretensis" from the straits.',
    certainty: 'Confirmed',
    transport: 'Land',
    coord_x: 48, coord_y: 45, coord_lat: 38.1938, coord_lng: 15.554,
    book_title: "Octavian's War Against Sextus Pompeius",
    book_author: 'John W. Welch',
    book_url: 'https://www.amazon.com/s?k=Augustus+Sextus+Pompey+Sicily+war',
  },
  {
    id: 'stage-2',
    legion_id: 'leg-x-fretensis',
    year: '31 BC',
    location: 'Actium',
    description: 'Participated in the naval Battle of Actium against Mark Antony and Cleopatra.',
    certainty: 'Confirmed',
    transport: 'Sea',
    coord_x: 55, coord_y: 48, coord_lat: 38.9317, coord_lng: 20.7692,
    book_title: 'Actium 31 BC: Downfall of Antony and Cleopatra',
    book_author: 'Si Sheppard',
    book_url: 'https://www.amazon.com/s?k=Actium+31+BC+Si+Sheppard',
  },
  {
    id: 'stage-3',
    legion_id: 'leg-x-fretensis',
    year: 'c. 6 AD',
    location: 'Syria',
    description: 'Stationed in the East to guard the Parthian frontier. Based at Cyrrhus.',
    certainty: 'Confirmed',
    transport: 'Sea',
    coord_x: 75, coord_y: 40, coord_lat: 36.7456, coord_lng: 36.9536,
    book_title: 'Rome and the Parthians: Empires in Conflict',
    book_author: 'Adrian Goldsworthy',
    book_url: 'https://www.amazon.com/s?k=Rome+Parthians+Goldsworthy',
  },
  {
    id: 'stage-4',
    legion_id: 'leg-x-fretensis',
    year: '66-70 AD',
    location: 'Judaea / Jerusalem',
    description: 'Primary force in the First Jewish-Roman War. Executed the final breach of Jerusalem.',
    certainty: 'Confirmed',
    transport: 'Land',
    coord_x: 78, coord_y: 52, coord_lat: 31.7683, coord_lng: 35.2137,
    book_title: 'The Jewish War',
    book_author: 'Flavius Josephus',
    book_url: 'https://www.amazon.com/s?k=The+Jewish+War+Josephus',
  },
  {
    id: 'stage-5',
    legion_id: 'leg-x-fretensis',
    year: '73 AD',
    location: 'Masada',
    description: 'Constructed the famous ramp and besieged the final zealot stronghold at Masada.',
    certainty: 'Confirmed',
    transport: 'Land',
    coord_x: 78, coord_y: 55, coord_lat: 31.315, coord_lng: 35.3533,
    book_title: 'Masada: From Jewish Revolt to Modern Myth',
    book_author: 'Jodi Magness',
    book_url: 'https://www.amazon.com/s?k=Masada+Jodi+Magness',
  },
  {
    id: 'stage-6',
    legion_id: 'leg-x-fretensis',
    year: 'AD 132-135',
    location: 'Aelia Capitolina',
    description: 'Transferred to permanent stationing at the new colony of Aelia Capitolina (Jerusalem) following the Bar Kokhba revolt.',
    certainty: 'Confirmed',
    transport: 'Land',
    coord_x: 78, coord_y: 52, coord_lat: 31.7833, coord_lng: 35.2167,
    book_title: 'Bar Kokhba: The Rediscovery of the Legendary Hero',
    book_author: 'Yigael Yadin',
    book_url: 'https://www.amazon.com/s?k=Bar+Kokhba+Yigael+Yadin',
  },
  {
    id: 'stage-7',
    legion_id: 'leg-x-fretensis',
    year: 'AD 410',
    location: 'Aila (Red Sea)',
    description: 'Final secure attestation in the Notitia Dignitatum, guarding the borders of the Red Sea.',
    certainty: 'Probable',
    transport: 'Land',
    coord_x: 80, coord_y: 60, coord_lat: 29.5267, coord_lng: 35.0078,
    book_title: 'The Fall of the Roman Empire',
    book_author: 'Peter Heather',
    book_url: 'https://www.amazon.com/s?k=Fall+Roman+Empire+Peter+Heather',
  },
];

// ── POIs ──────────────────────────────────────────────────────────────────────

const pois = [
  {
    id: 'poi-1-1', stage_id: 'stage-1',
    type: 'Camp', name: 'Messina Garrison',
    description: 'Initial training grounds for the newly raised legion.',
    coord_lat: 38.1938, coord_lng: 15.554,
    image_url: 'roman_legion_camp_sicily',
    intel_supply_line: 'Mainland Italy-Sicily Grain Route',
    intel_distance: '0 km (Raised Local)',
    intel_terrain: 'Coastal Plains',
    intel_estimated_strength: null,
    book_title: 'Augustus: First Emperor of Rome',
    book_author: 'Adrian Goldsworthy',
    book_url: 'https://www.amazon.com/s?k=Augustus+First+Emperor+Rome+Goldsworthy',
  },
  {
    id: 'poi-2-1', stage_id: 'stage-2',
    type: 'Battle', name: 'Battle of Actium',
    description: "Decisive naval engagement where the legion served aboard Octavian's fleet.",
    coord_lat: 38.9317, coord_lng: 20.7692,
    image_url: 'battle_of_actium_naval',
    intel_supply_line: 'Roman Fleet Support',
    intel_distance: '480 km (Sea)',
    intel_terrain: 'Open Sea / Archipelago',
    intel_estimated_strength: '12,000 Marines/Legionaries',
    book_title: 'Actium 31 BC: Downfall of Antony and Cleopatra',
    book_author: 'Si Sheppard',
    book_url: 'https://www.amazon.com/s?k=Actium+31+BC+Si+Sheppard',
  },
  {
    id: 'poi-3-1', stage_id: 'stage-3',
    type: 'Fortress', name: 'Cyrrhus Base',
    description: 'Main headquarters for the legion in northern Syria.',
    coord_lat: 36.7456, coord_lng: 36.9536,
    image_url: 'roman_fortress_syria',
    intel_supply_line: 'Euphrates Frontier Road',
    intel_distance: '1,200 km (Mixed)',
    intel_terrain: 'Semi-Arid Steppe',
    intel_estimated_strength: '5,000 Heavy Infantry',
    book_title: 'Rome and the Parthians: Empires in Conflict',
    book_author: 'Adrian Goldsworthy',
    book_url: 'https://www.amazon.com/s?k=Rome+Parthians+Goldsworthy',
  },
  {
    id: 'poi-4-1', stage_id: 'stage-4',
    type: 'Siege', name: 'Siege of Jerusalem',
    description: 'The legion was responsible for breaching the third wall.',
    coord_lat: 31.7767, coord_lng: 35.2345,
    image_url: 'siege_of_jerusalem_breach',
    intel_supply_line: 'Caesarea Maritima Road',
    intel_distance: '65 km (Land)',
    intel_terrain: 'Judaean Hills',
    intel_estimated_strength: '15,000 (with Auxiliaries)',
    book_title: 'The Jewish War',
    book_author: 'Flavius Josephus',
    book_url: 'https://www.amazon.com/s?k=The+Jewish+War+Josephus',
  },
  {
    id: 'poi-4-2', stage_id: 'stage-4',
    type: 'Camp', name: 'Mount Scopus Camp',
    description: 'Main Roman encampment overlooking the city.',
    coord_lat: 31.7917, coord_lng: 35.2444,
    image_url: 'roman_siege_camp_overlook',
    intel_supply_line: 'Fortified Hilltop Supplies',
    intel_distance: '2 km',
    intel_terrain: 'High Altitude Overlook',
    intel_estimated_strength: null,
    book_title: 'The Jewish War',
    book_author: 'Flavius Josephus',
    book_url: 'https://www.amazon.com/s?k=The+Jewish+War+Josephus',
  },
  {
    id: 'poi-5-1', stage_id: 'stage-5',
    type: 'Camp', name: 'Camp F',
    description: 'One of the eight siege camps built by the Tenth Legion.',
    coord_lat: 31.3155, coord_lng: 35.352,
    image_url: 'siege_camp_masada',
    intel_supply_line: 'Dead Sea Maritime Chain',
    intel_distance: '100 km',
    intel_terrain: 'Desert Basin',
    intel_estimated_strength: null,
    book_title: 'Masada: From Jewish Revolt to Modern Myth',
    book_author: 'Jodi Magness',
    book_url: 'https://www.amazon.com/s?k=Masada+Jodi+Magness',
  },
  {
    id: 'poi-5-2', stage_id: 'stage-5',
    type: 'Monument', name: 'The Roman Ramp',
    description: 'A massive earthen ramp constructed to facilitate the final assault.',
    coord_lat: 31.3138, coord_lng: 35.3525,
    image_url: 'masada_roman_ramp',
    intel_supply_line: 'Local Salt-Route Logistics',
    intel_distance: 'N/A',
    intel_terrain: 'Sheer Cliff Base',
    intel_estimated_strength: null,
    book_title: 'Masada: From Jewish Revolt to Modern Myth',
    book_author: 'Jodi Magness',
    book_url: 'https://www.amazon.com/s?k=Masada+Jodi+Magness',
  },
  {
    id: 'poi-6-1', stage_id: 'stage-6',
    type: 'Fortress', name: 'Legionary Fortress',
    description: 'Located in the southwest of the city, near the current Armenian Quarter.',
    coord_lat: 31.7744, coord_lng: 35.2289,
    image_url: null,
    intel_supply_line: null, intel_distance: null, intel_terrain: null, intel_estimated_strength: null,
    book_title: 'Bar Kokhba: The Rediscovery of the Legendary Hero',
    book_author: 'Yigael Yadin',
    book_url: 'https://www.amazon.com/s?k=Bar+Kokhba+Yigael+Yadin',
  },
  {
    id: 'poi-7-1', stage_id: 'stage-7',
    type: 'Fortress', name: 'Fortress of Aila',
    description: 'A coastal fort built to secure the spice trade and imperial borders.',
    coord_lat: 29.5267, coord_lng: 35.0078,
    image_url: null,
    intel_supply_line: null, intel_distance: null, intel_terrain: null, intel_estimated_strength: null,
    book_title: 'The Fall of the Roman Empire',
    book_author: 'Peter Heather',
    book_url: 'https://www.amazon.com/s?k=Fall+Roman+Empire+Peter+Heather',
  },
];

// ── Run ───────────────────────────────────────────────────────────────────────

async function seed() {
  console.log('Seeding legions...');
  const { error: le } = await supabase.from('legions').upsert(legions);
  if (le) { console.error('legions:', le.message); process.exit(1); }
  console.log(`  ✓ ${legions.length} legions`);

  console.log('Seeding movement_stages...');
  const { error: se } = await supabase.from('movement_stages').upsert(stages);
  if (se) { console.error('movement_stages:', se.message); process.exit(1); }
  console.log(`  ✓ ${stages.length} stages`);

  console.log('Seeding pois...');
  const { error: pe } = await supabase.from('pois').upsert(pois);
  if (pe) { console.error('pois:', pe.message); process.exit(1); }
  console.log(`  ✓ ${pois.length} POIs`);

  console.log('Done.');
}

seed();
